# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          - '0.0.0.0:8001'

  - job_name: math
    static_configs:
      - targets:
          - '0.0.0.0:8002'